language: objective-c
osx_image: xcode8

script:
    - set -o pipefail && xcodebuild clean build test -scheme ChainedAnimation -destination "OS=10.0,name=iPhone 7" | xcpretty
after_script:
    - bash <(curl -s https://codecov.io/bash)
