language: objective-c
osx_image: beta-xcode6.3
install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
    - set -o pipefail && xcodebuild test -workspace Example/ChainedAnimation.xcworkspace -scheme ChainedAnimation-Example -destination "OS=8.3,name=iPhone 6" -sdk "iphonesimulator8.3"  ONLY_ACTIVE_ARCH=NO | xcpretty -c
    - pod lib lint --quick
