language: objective-c
osx_image: osx_image: xcode7
install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
    - set -o pipefail && xcodebuild test -workspace Example/ChainedAnimation.xcworkspace -scheme ChainedAnimation-Example -destination "OS=8.3,name=iPhone 6" -sdk "iphonesimulator9.0"  ONLY_ACTIVE_ARCH=NO | xcpretty -c
    - pod lib lint --quick
