language: objective-c
osx_image: xcode8
install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
    - set -o pipefail && xcodebuild clean build test -scheme ChainedAnimation -destination "OS=10.0,name=iPhone 7" | xcpretty -c
